/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Articles: () => import('#controllers/admin/articles_controller'),
    Categories: () => import('#controllers/admin/categories_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Home: () => import('#controllers/admin/home_controller'),
    Media: () => import('#controllers/admin/media_controller'),
    Messages: () => import('#controllers/admin/messages_controller'),
    Pages: () => import('#controllers/admin/pages_controller'),
    Projects: () => import('#controllers/admin/projects_controller'),
    Security: () => import('#controllers/admin/security_controller'),
    Session: () => import('#controllers/admin/session_controller'),
    Tags: () => import('#controllers/admin/tags_controller'),
    Talks: () => import('#controllers/admin/talks_controller'),
    Technologies: () => import('#controllers/admin/technologies_controller'),
  },
  Blog: () => import('#controllers/blog_controller'),
  Contact: () => import('#controllers/contact_controller'),
  Cv: () => import('#controllers/cv_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Home: () => import('#controllers/home_controller'),
  Legal: () => import('#controllers/legal_controller'),
  Llms: () => import('#controllers/llms_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Seo: () => import('#controllers/seo_controller'),
  Talks: () => import('#controllers/talks_controller'),
  Technologies: () => import('#controllers/technologies_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
