/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import ContactMessageReceived from '#events/contact_message_received'

export const events = {
  ContactMessageReceived: ContactMessageReceived,
}
