/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArticleProjectSchema extends BaseModel {
  static $columns = ['articleId', 'id', 'projectId'] as const
  $columns = ArticleProjectSchema.$columns
  @column()
  declare articleId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
}

export class ArticleTagSchema extends BaseModel {
  static $columns = ['articleId', 'id', 'tagId'] as const
  $columns = ArticleTagSchema.$columns
  @column()
  declare articleId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tagId: number
}

export class ArticleTranslationSchema extends BaseModel {
  static $columns = [
    'articleId',
    'contentHtml',
    'contentMarkdown',
    'createdAt',
    'id',
    'locale',
    'summary',
    'title',
    'updatedAt',
  ] as const
  $columns = ArticleTranslationSchema.$columns
  @column()
  declare articleId: number
  @column()
  declare contentHtml: string
  @column()
  declare contentMarkdown: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ArticleSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'coverMediaId',
    'createdAt',
    'id',
    'publishedAt',
    'readingTime',
    'slug',
    'status',
    'updatedAt',
  ] as const
  $columns = ArticleSchema.$columns
  @column()
  declare categoryId: number | null
  @column()
  declare coverMediaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readingTime: number
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategoryTranslationSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'id', 'locale', 'name', 'updatedAt'] as const
  $columns = CategoryTranslationSchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactMessageSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'email', 'id', 'name', 'readAt', 'updatedAt'] as const
  $columns = ContactMessageSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaSchema extends BaseModel {
  static $columns = [
    'alt',
    'createdAt',
    'height',
    'id',
    'key',
    'mimeType',
    'originalName',
    'size',
    'updatedAt',
    'variants',
    'width',
  ] as const
  $columns = MediaSchema.$columns
  @column()
  declare alt: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variants: any
  @column()
  declare width: number
}

export class ProjectLinkSchema extends BaseModel {
  static $columns = ['id', 'label', 'position', 'projectId', 'type', 'url'] as const
  $columns = ProjectLinkSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare position: number
  @column()
  declare projectId: number
  @column()
  declare type: string
  @column()
  declare url: string
}

export class ProjectTechnologySchema extends BaseModel {
  static $columns = ['id', 'projectId', 'technologyId'] as const
  $columns = ProjectTechnologySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare technologyId: number
}

export class ProjectTranslationSchema extends BaseModel {
  static $columns = [
    'contentHtml',
    'contentMarkdown',
    'createdAt',
    'id',
    'locale',
    'projectId',
    'summary',
    'title',
    'updatedAt',
  ] as const
  $columns = ProjectTranslationSchema.$columns
  @column()
  declare contentHtml: string
  @column()
  declare contentMarkdown: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare projectId: number
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    'coverMediaId',
    'createdAt',
    'endedAt',
    'featured',
    'id',
    'publishedAt',
    'slug',
    'startedAt',
    'status',
    'updatedAt',
  ] as const
  $columns = ProjectSchema.$columns
  @column()
  declare coverMediaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endedAt: DateTime | null
  @column()
  declare featured: boolean
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column.date()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class TagTranslationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'locale', 'name', 'tagId', 'updatedAt'] as const
  $columns = TagTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare name: string
  @column()
  declare tagId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TalkLinkSchema extends BaseModel {
  static $columns = ['id', 'label', 'position', 'talkId', 'type', 'url'] as const
  $columns = TalkLinkSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare position: number
  @column()
  declare talkId: number
  @column()
  declare type: string
  @column()
  declare url: string
}

export class TalkTechnologySchema extends BaseModel {
  static $columns = ['id', 'talkId', 'technologyId'] as const
  $columns = TalkTechnologySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare talkId: number
  @column()
  declare technologyId: number
}

export class TalkTranslationSchema extends BaseModel {
  static $columns = [
    'contentHtml',
    'contentMarkdown',
    'createdAt',
    'id',
    'locale',
    'summary',
    'talkId',
    'title',
    'updatedAt',
  ] as const
  $columns = TalkTranslationSchema.$columns
  @column()
  declare contentHtml: string
  @column()
  declare contentMarkdown: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare summary: string
  @column()
  declare talkId: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TalkSchema extends BaseModel {
  static $columns = [
    'city',
    'coverMediaId',
    'createdAt',
    'eventDate',
    'eventName',
    'id',
    'publishedAt',
    'slug',
    'status',
    'updatedAt',
  ] as const
  $columns = TalkSchema.$columns
  @column()
  declare city: string
  @column()
  declare coverMediaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare eventDate: DateTime
  @column()
  declare eventName: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TechnologySchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'id',
    'logoMediaId',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = TechnologySchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoMediaId: number | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TechnologyTranslationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'locale',
    'technologyId',
    'updatedAt',
  ] as const
  $columns = TechnologyTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare technologyId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TimelineEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'position', 'updatedAt'] as const
  $columns = TimelineEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TimelineEntryTranslationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'locale',
    'period',
    'place',
    'timelineEntryId',
    'title',
    'updatedAt',
  ] as const
  $columns = TimelineEntryTranslationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare period: string
  @column()
  declare place: string
  @column()
  declare timelineEntryId: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'recoveryCodes',
    'totpSecret',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare recoveryCodes: any | null
  @column()
  declare totpSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
