/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type BlogArticleCardTransformer from '#app/blog/transformers/article_card_transformer'
import type BlogArticleDetailTransformer from '#app/blog/transformers/article_detail_transformer'
import type IdentityUserTransformer from '#app/identity/transformers/user_transformer'
import type PortfolioProjectCardTransformer from '#app/portfolio/transformers/project_card_transformer'
import type PortfolioProjectDetailTransformer from '#app/portfolio/transformers/project_detail_transformer'
import type TalksTalkCardTransformer from '#app/talks/transformers/talk_card_transformer'
import type TalksTalkDetailTransformer from '#app/talks/transformers/talk_detail_transformer'
import type TechnologiesTechnologyCardTransformer from '#app/technologies/transformers/technology_card_transformer'
import type TechnologiesTechnologyDetailTransformer from '#app/technologies/transformers/technology_detail_transformer'
import type InertiaMiddleware from '#app/middleware/inertia_middleware'

export namespace Data {
  export namespace Blog {
    export type ArticleCard = InferData<BlogArticleCardTransformer>
    export namespace ArticleCard {
      export type Variants = InferVariants<BlogArticleCardTransformer>
    }
    export type ArticleDetail = InferData<BlogArticleDetailTransformer>
    export namespace ArticleDetail {
      export type Variants = InferVariants<BlogArticleDetailTransformer>
    }
  }
  export namespace Identity {
    export type User = InferData<IdentityUserTransformer>
    export namespace User {
      export type Variants = InferVariants<IdentityUserTransformer>
    }
  }
  export namespace Portfolio {
    export type ProjectCard = InferData<PortfolioProjectCardTransformer>
    export namespace ProjectCard {
      export type Variants = InferVariants<PortfolioProjectCardTransformer>
    }
    export type ProjectDetail = InferData<PortfolioProjectDetailTransformer>
    export namespace ProjectDetail {
      export type Variants = InferVariants<PortfolioProjectDetailTransformer>
    }
  }
  export namespace Talks {
    export type TalkCard = InferData<TalksTalkCardTransformer>
    export namespace TalkCard {
      export type Variants = InferVariants<TalksTalkCardTransformer>
    }
    export type TalkDetail = InferData<TalksTalkDetailTransformer>
    export namespace TalkDetail {
      export type Variants = InferVariants<TalksTalkDetailTransformer>
    }
  }
  export namespace Technologies {
    export type TechnologyCard = InferData<TechnologiesTechnologyCardTransformer>
    export namespace TechnologyCard {
      export type Variants = InferVariants<TechnologiesTechnologyCardTransformer>
    }
    export type TechnologyDetail = InferData<TechnologiesTechnologyDetailTransformer>
    export namespace TechnologyDetail {
      export type Variants = InferVariants<TechnologiesTechnologyDetailTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
