import type { HttpContext } from '@adonisjs/core/http'
import drive from '@adonisjs/drive/services/main'
import MediaService from '#services/media_service'

/**
 * Serves media library files from the Drive disk. Both URL segments
 * are strictly validated, so only files generated by MediaService
 * can be reached.
 */
const KEY_PATTERN = /^[a-z0-9]{10,32}$/
const FILE_PATTERN = /^(original|w\d{3,4})\.webp$/

export default class UploadsController {
  async show({ params, response }: HttpContext) {
    const { key, file } = params

    if (!KEY_PATTERN.test(key) || !FILE_PATTERN.test(file)) {
      return response.notFound('Not found')
    }

    const disk = drive.use()
    const diskKey = MediaService.key(key, file)
    if (!(await disk.exists(diskKey))) {
      return response.notFound('Not found')
    }

    response.header('content-type', 'image/webp')
    response.header('cache-control', 'public, max-age=31536000, immutable')
    return response.stream(await disk.getStream(diskKey))
  }
}
