import type { HttpContext } from '@adonisjs/core/http'
import drive from '@adonisjs/drive/services/main'
import Media from '#models/media'
import MediaService, { DOCUMENT_FILE } from '#services/media_service'

/**
 * Serves media library files from the Drive disk. Both URL segments
 * are strictly validated, so only files generated by MediaService
 * can be reached.
 */
const KEY_PATTERN = /^[a-z0-9]{10,32}$/
const FILE_PATTERN = /^(original|w\d{3,4})\.webp$/

/**
 * Download name of a document: the uploaded name stripped of
 * anything that could break out of the content-disposition header.
 */
function downloadName(originalName: string) {
  const cleaned = originalName
    .replace(/[^\w.\- ]+/g, '')
    .trim()
    .slice(0, 100)
  if (!cleaned || cleaned === '.pdf') {
    return DOCUMENT_FILE
  }
  return cleaned.toLowerCase().endsWith('.pdf') ? cleaned : `${cleaned}.pdf`
}

export default class UploadsController {
  async show({ params, response }: HttpContext) {
    const { key, file } = params
    const isDocument = file === DOCUMENT_FILE

    if (!KEY_PATTERN.test(key) || !(isDocument || FILE_PATTERN.test(file))) {
      return response.notFound('Not found')
    }

    const disk = drive.use()
    const diskKey = MediaService.key(key, file)
    if (!(await disk.exists(diskKey))) {
      return response.notFound('Not found')
    }

    /**
     * Documents open in the browser viewer and are saved under the
     * name they were uploaded with, not the generated one.
     */
    if (isDocument) {
      const media = await Media.findBy('key', key)
      response.header('content-type', 'application/pdf')
      response.header(
        'content-disposition',
        `inline; filename="${downloadName(media?.originalName ?? DOCUMENT_FILE)}"`
      )
    } else {
      response.header('content-type', 'image/webp')
    }

    response.header('cache-control', 'public, max-age=31536000, immutable')
    return response.stream(await disk.getStream(diskKey))
  }
}
